name: Integration Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Process
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%\win
          run.bat
          
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            win/server/main_log.txt
            win/server/carbon/plugins/IntegrationTests.cs
